spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl
    username: root
    password: 19920315
    max-active: 20
    min-idle: 8
  main:
    banner-mode: CONSOLE
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
logging: 
  level: 
    root: WARN
    org.springframework.security: DEBUG